package net.mindsoup.pathfindercharactersheet.pf.skills;

public enum PfSkills {
	ACROBATICS, APPRAISE, BLUFF, CLIMB, CRAFT, DIPLOMACY, DISABLE_DEVICE, DISGUISE, ESCAPE_ARTIST, FLY, HANDLE_ANIMAL, HEAL, INTIMIDATE, KNOWLEDGE_ARCANA, KNOWLEDGE_DUNGEONEERING, KNOWLEDGE_ENGINEERING, KNOWLEDGE_GEOGRAPHY, KNOWLEDGE_HISTORY, KNOWLEDGE_LOCAL, KNOWLEDGE_NATURE, KNOWLEDGE_NOBILITY, KNOWLEDGE_PLANES, KNOWLEDGE_RELEIGION, LINGUISTICS, PERCEPTION, PERFORM, PROFESSION, RIDE, SENSE_MOTIVE, SLEIGHT_OF_HAND, SPELLCRAFT, STEALTH, SURVIVAL, SWIM, USE_MAGIC_DEVICE
}
